### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by sonyerhcssa** [sonyerhcssa/protospace-37382#1]
# URL
https://protospace-37382.herokuapp.com/

**Comment by soll02solglas** [comment]
@sonyerhcssa さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] ログアウト状態のユーザーであっても、トップページ・プロトタイプ詳細ページ・ユーザー詳細ページ・ユーザー新規登録ページ・ログインページには遷移できるようにしましょう。
→現状ログアウト状態だと一覧ページからプロトタイプの詳細ページに遷移しようとするとログインページにリダイレクトされてしまいます。

- [x] ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するようにしましょう。
→現状ログアウト状態でプロトタイプ一覧ページのユーザー名をクリックすると、ログインページに遷移してしまいます。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by sonyerhcssa** [comment]
確認ありがとうございます。
指摘部分の修正を行いました。
ご確認お願いします。

**Comment by snkw-works** [comment]
@sonyerhcssa さん、修正とご提出ありがとうございます‼︎
正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）

**Comment by sonyerhcssa** [comment]
ありがとうございました。
